# Generated by Django 4.2.9 on 2025-02-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_rename_user_customeuser_alter_passwordmaster_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='user_name',
        ),
    ]
